### ISSUE TITLE
Exception adding cookie to plumadriver

### ISSUE THREAD

**Issue by adamjordannexj** [Seneca-CDOT/plumadriver#15]
Our basic strategy was to:

1. Login to the application directly with Chrome via basic auth.
2. Use getCookies and store the resultant set of cookies.
3. Get an instance of PlumaDriver, and navigate to some site on the domain, 
4. Apply those stored cookies via addCookie.
5. Navigate to the application proper, you're now logged in.

It looks like we're failing on step 4. Replacing PlumaDriver with the Firefox GeckoDriver works properly. I thought maybe this method of getting the cookies was a bit janky, so I replaced it with the 'proper' method; using OkHttp to create a request with the authentication, and parsing out the cookies from the response headers. This gives me the same error. Firefox continues to work.

I've attached a partial stack trace below; if there's any more information you need, please let me know.

org.openqa.selenium.InvalidArgumentException: The arguments passed to undefined are either invalid or malformed
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'TOR-DT-AJORDAN1', ip: '192.168.61.28', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.PlumaDriver
Capabilities {acceptInsecureCerts: true, browserName: pluma, browserVersion: v1.0, javascriptEnabled: true, pageLoadStrategy: normal, platform: UNIX, platformName: UNIX, plm:plumaOptions: {}, proxy: Proxy(), setWindowRect: false, timeouts: {implicit: 0, pageLoad: 30000, script: 30000}}
Session ID: 0c9d37b1-82f1-11e9-907f-c1ce7518a251
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions.addCookie(RemoteWebDriver.java:682)
at nexj.core.testing.ui.application.Application.login(Application.java:604)
at nexj.core.testing.ui.application.AFLApplication.login(AFLApplication.java:174)
at nexj.core.testing.ui.application.AFLApplication.login(AFLApplication.java:145)

**Comment by miggs125** [comment]
Hey @adamjordannexj, plumadriver produces a pluma_error_log.txt file in the project's root directory. Could you please provide this file, the script, and if possible, the cookies added that caused the issue?

**Comment by adamjordannexj** [comment]
The two headers were;
NexJ-Authentication-Token=ziGIRQZBsXlz5/UTh5laawFdAPlDcKCJ5pQxTH98aqg2; Domain=.nexjsystems.local; Path=/; HttpOnly
NexJ-Logout-Date=1559845011791; Domain=.nexjsystems.local; Path=/

pluma_error_log.txt;
[pluma_error_log.txt](https://github.com/Seneca-CDOT/plumadriver/files/3238359/pluma_error_log.txt)

Which script were you looking for?

**Comment by miggs125** [comment]
The selenium script

**Comment by adamjordannexj** [comment]
[script.txt](https://github.com/Seneca-CDOT/plumadriver/files/3238444/script.txt)

createWebDriver() in this instance will return a simple new PlumaDriver(new PlumaOptions());
The set of cookies retrieved seem fine, since both Chrome and Firefox log in properly with them, but just in case, we parse the headers (of which I gave you an example) into their constituent pieces, and create them as new Cookie(name, value, domain, path, null, false, httpOnly);

**Comment by miggs125** [comment]
@adamjordannexj I have made some changes which appear to have fixed the bug. I still need to do more thorough testing before merging with master. However, you can build plumadriver with the code found in [this branch](https://github.com/Seneca-CDOT/plumadriver/tree/issue15-addCookieException). You can try using the build with this code and see if you are now able to add a cookie.

**Comment by adamjordannexj** [comment]
This seems to fix the issue with adding a cookie on our side, thank you.
